### ISSUE TITLE
Events/projects

### ISSUE THREAD

**Issue by JohannesAnd** [strekmann/nidarholmjs#154]
I have thought about this for a while, and I more or less stumbled upon this repo when I rembembered that you made this. I think there should be a closer connection between events and projects. A project should probably be connected to several rehershal-events and a concert-event. This way you don't have two places to look for the same information. I suggest that the project contains all of the information, but if you click on a rehershal you should get the music wich belongs to the projects that is to be worked on and the short info, as well as cake and percussion-duties. As it is now I feel like I have to go several places just to make sure I didn't miss anything.

**Comment by sigurdga** [comment]
A very valid point. I have thought a lot about this myself. Projects and events are now connected, and this version of the interface enforced this as a new thing, but needed to support the old case. But bringing contents from the project into the event is a new thought, and very useful. Thanks for the input.
